package.json, size-stats.json, src/phone-number-field.tsx, yarn.lock
=> feat(PhoneNumberField): Update libphonenumber library and use new method for e164 formatting

size-stats.json, src/feedback-screen.tsx, src/fixed-footer-layout.tsx
Related WebApp PR: https://github.com/Telefonica/webapp/pull/577
Problem:
https://user-images.githubusercontent.com/579417/122053112-be12b000-cde6-11eb-8197-2a320aead73e.mp4
With this fix:
**(updated)**
https://user-images.githubusercontent.com/579417/122101502-abaf6b00-ce14-11eb-8365-6860c8342fe6.mp4
Also verified that nothing breaks in appointments booking
=> Fix(FixedFooterLayout, FeedbackScreen): update some styles that were causing problems in page transition animations

src/header.tsx
=> fix(HeaderLayout): remove right padding from extra

doc/texts.md, src/__tests__/credit-card-fields-test.tsx, src/credit-card-expiration-field.tsx, src/theme.tsx
Fix cc expiration field error message and add tests
jira: WEB-185
=> fix(CreditCardExpirationField): show mandatory field error message when empty

flow-defs/loading-bar.js.flow, flow-defs/progress-bar.js.flow, size-stats.json, src/callout.tsx, src/card.tsx, src/credit-card-fields.tsx, src/divider.tsx, src/empty-state-card.tsx, src/empty-state-screen.tsx, src/header.tsx, src/highlighted-card.tsx, src/loading-bar.tsx, src/menu.tsx, src/navigation-breadcrumbs.tsx, src/placeholder.tsx, src/popover.tsx, src/progress-bar.tsx, src/select.tsx, src/snackbar.tsx, src/spinner.tsx, src/stepper.tsx, src/tabs.tsx, src/text-field-components.tsx
=> fix(types): remove implicit children prop from some components

size-stats.json, src/feedback-screen.tsx
WEB-269
If someone has access to a Galaxy S20+, I can prepare a webapp with suffix to validate the fix
=> WEB-269 Tentative fix

CONTRIBUTING.md, flow-defs/menu.js.flow, size-stats.json, src/__stories__/menu-story.tsx, src/__tests__/menu-test.tsx, src/menu.tsx
https://user-images.githubusercontent.com/4282123/127829778-0baeb0fb-220d-4b82-abca-e16edf28d39d.mov
=> feat(Menu): Expose function to close menu

flow-defs/menu.js.flow, playroom/snippets.tsx, size-stats.json, src/__stories__/menu-story.tsx, src/menu.tsx
We use this component in several places in the CMS, and we have some issues when the Menu appears on the right of the screen. We want to optionally allow select the align of the Menu items.
=> feat(Menu): new direction prop

playroom/snippets.tsx
Also I changed some text styles in MasterDetailLayout snippet
=> fix(snippets): change some deprecated icons

playroom/snippets.tsx
Changed asset prop to icon prop.
=> wrong prop applying in callout

flow-defs/card.js.flow, size-stats.json, src/__stories__/media-card-story.tsx, src/card.tsx
=> feat(MediaCard): make description optional

src/switch-component.tsx
to be fixed in https://jira.tid.es/browse/WEB-386
=> fix(Switch): Revert event cancel in switch change

src/dialog.tsx
fixes: WEB-258
Demo: https://mistica-web-d4xqmjdms-tuentisre.vercel.app/playroom/preview/#?code=N4Igxg9gJgpiBcIA8AhArgFwxAdgBQCcBLAWwEMCBPAAl0JgGcGBeYACgEprmA+ayHADMiBEm2DUSjBmQDmMeNQA6IAIJgYABwwVa-Mjg0AbCgH4V1AL4dLPJTmrUAwrmGiK9pAHp0WOsXIqOxwQABoQDAALGCkEEABZCAA3IgYdAhBLIA
=> fix(Dialog): race condition closing it before open transition end

src/dialog.tsx
10% animation speed:
https://user-images.githubusercontent.com/1849576/147940121-eafa7954-f16c-4cd7-bf47-3f0efc527206.mp4
=> fix(Dialog): overlay fadeout animation

src/menu.tsx
No visual changes, only fixing a bug.
Attached a video of the issue found (menu usage with changing render, autocomplete component)
https://user-images.githubusercontent.com/6709771/149767985-43a5fde0-4d6e-4b6d-a242-f406a39cc994.mp4
This componente can be tested in Menu component and also in Custom field example (both in storybook)
=> fix(Menu): Menu component improvements

flow-defs/dialog.js.flow, flow-defs/theme.js.flow, size-stats.json, src/dialog.tsx, src/theme-context-provider.tsx, src/theme.tsx
* [Normal example (back button closes)](https://mistica-web-if02fu303-tuentisre.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AhArgFwxAdgBQCcBLAWwEMCBPAAl0JgGcGBeYACgEprmA%2BasgDYwCGNsGolGDMgHMY8agB0QACwgCyy6gF8O2nopzVqAZTUB3fkJGGkAenRY6xclQM4QAGhAYVMSQwIANogALIQAG5EDBgUIAC63uZEUL6B8EEA7ABsABzx2kA)
* [Disabling history update](https://mistica-web-if02fu303-tuentisre.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AVAFjAtjAwhAdgC4wAehACgE4QBuAlrJQDr4AErhG2AvMMC%2B3YBnANZ188VgHMYhALK06QwgENKAZTH4AFAEoANAMF0AjAA4JrYKwA2EMCpsxJTEDCEBaAKLrX%2B1gAOaAQwAHIArpgARjCUAGIQlJgqhITiUgBKMFJ0BHiwLiA%2BrqwAvoZsguH4yipRTgD6UEp1TgASSoSJAJ4AqgFQKTAAkvgAInSOEFJCkoSU4TAV7KWlLAB8RkgAQuGpBFR0yZTdrAeU7kK8eqzc66yOsYTa1thCQioyhcE2KiWlulKm0q7HUwQA7g8nJRCFsAPS7fb4Q7HbrApBw9BYXAEYhkKiKRjAkD6ECcbFCBAAbRACnotUoIAAuqTwQxOJT4FSAO …
=> feat(Dialog): allow disable history update in dialogs

flow-defs/image.js.flow, flow-defs/tag.js.flow, flow-defs/text.js.flow, flow-defs/video.js.flow, playroom/snippets.tsx, size-stats.json, src/__stories__/media-card-story.tsx, src/__stories__/tag-story.tsx, src/__stories__/text-story.tsx, src/image.tsx, src/tag.tsx, src/text.tsx, src/video.tsx
Add `dataAttributes` to Tag, Image, Video, Text
=> feat(Image, Text, Video, Tag): add dataAttributes prop

src/popover.tsx
Popover has wrong styles for title weight and description colors
=> fix(Popover): text styles

src/fixed-footer-layout.tsx
Little changes to make more visible shadows in this component
=> fix(FixedFooterLayout): shadow style

src/list.tsx
=> fix(Row): remove cursor pointer on non interactive rows

src/chip.tsx
=> fix(Chip): disable user select in interactive Chips

flow-defs/theme.js.flow, flow-defs/utils/media-queries.js.flow, flow-defs/utils/platform.js.flow, src/button.tsx, src/carousel.tsx, src/theme.tsx, src/utils/media-queries.tsx
This aims to prevent from Mística the same issue detected at ACCOUNT-17156.
=> fix(MediaQuery): Improve media query for touchable-only devices

src/popover.tsx, src/tooltip.tsx
Popover and tooltip was using `background` instead of `backgroundContainer`
=> fix popover & tooltip background

flow-defs/grid-layout.js.flow, playroom/snippets.tsx, src/__stories__/grid-layout-story.tsx, src/grid-layout.tsx
Requested by O2 España
https://github.com/Telefonica/mistica-design/issues/639
=> feat(GridLayoutNew): new 3+9 template

src/skins/blau.tsx
It shouldn't be an impact on production
=> fix(Blau skin): backgroundSkeletonInverse color

.vscode/settings.json, .vscode/tasks.json, tsconfig.json
https://user-images.githubusercontent.com/4521712/189298181-1727826e-e14d-4c7c-a845-296ea6f6eecc.mp4
=> chore(VSCode): TypeScript watcher task

flow-defs/button.js.flow, flow-defs/index.js.flow, flow-defs/list.js.flow, flow-defs/touchable.js.flow, src/__tests__/button-test.tsx, src/button.tsx, src/index.tsx, src/list.tsx, src/touchable.tsx
=> feat(Button): use forwardRef

playroom/components.tsx, playroom/snippets.tsx
- Some snippets reorganization props following the component structure (cards)
- Random images in snippets all the time
- Resized the floating icon in PreviewTools
=> chore(Playroom): snippets improvements

codemods/theme-colors-codemod.js, flow-defs/index.js.flow, flow-defs/skins/skin-contract.css.js.flow, flow-defs/utils/color.js.flow, flow-overrides/skins/skin-contract.css.js.flow, src/index.tsx, src/utils/color.tsx
this will help to migrate codebases when we apply the first breaking change here https://github.com/Telefonica/mistica-web/issues/572
=> feat(colors): added codemod to migrate from theme.colors to skinVars.colors

src/__screenshot_tests__/tabs-screenshot-test.tsx, src/__stories__/tabs-story.tsx
=> chore(Tabs): fix broken story in dev

src/__acceptance_tests__/__ssr_pages__/carousel.tsx
This will unblock the CI, but we need a better solution (serve images locally for ssr tests and for storybook)
https://jira.tid.es/browse/WEB-776
=> chore(ssr-tests): replace broken url

src/__tests__/text-field-test.tsx, src/text-field.tsx
fixes https://github.com/Telefonica/mistica-web/issues/669
=> fix(TextField): maxLenght in controlled component

src/navigation-bar.tsx
=> feat(MainNavigationBar): don't show burger if there aren't 2 or more sections

src/card.tsx
master:
https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8BhAhgJwgVwM4wBsAdAOwAIyB3ASwBcALAIWwIJlt1IrpgFtcAvMACCGDGgCeAOgBmWXgApgZNiQDmDeGQBsZAL4AaMgoD6R6lAAeASjICAfMa4UySACJpaadBijOXZPQwaFAE1CQwQkgAKmhqZLQSAA6RRCBJ8hBp9gASwaHhMEgA9LFq9nr%2BLrR0bAJp0bUwaVUUsLhgGNRJNRAk9SBuMB1dPdR9LeQBZDCWtOJCrS4WlnYCAmQADGQA-E5T0y5IAAoEaGAw9BAEsBhkxfZLFLZaK2sbAIy7%2B4cBJ2cXK43GB3ILUNT0WhCABMmz090eB2mLzI2BIsBkhT8SIolRxZAARthaLQ%2Bot8RQkMwSX1jl1eJgJGRcAzWGRaRhhoJgApbA4yMA9HpEb8XMIwL0SE9XMVqaSSHTqAyMBIRdM8YciTSSAAZcIAayicr6epI%2BvZCs5uG5vLsjkFwtN%2BpKxt1BoqVQezms1jxXpIIAMIAYfGGCAA2iAALIQABu1FwXgwIAAukGaFAGLgIwBmbSbAwfTbQgAsKb0QA
this PR:
https://mistica-m7wlw1f4c-tuentisre.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8BhAhgJwgVwM4wBsAdAOwAIyB3ASwBcALAIWwIJlt1IrpgFtcAvMACCGDGgCeAOgBmWXgApgZNiQDmDeGQB …
=> fix(DataCard): style fixes for extra

src/__acceptance_tests__/__ssr_pages__/card.tsx, src/list.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-751)
=> fix(Row, BoxedRow): check for undefined value in props is incorrect

src/tabs.tsx
Removing disabled in active tab to allow interactivity (for accessibility reasons).
Issue: [Link](https://jira.tid.es/browse/WEB-578)
=> fix(Tabs): remove disabled in active tab

src/__tests__/button-test.tsx, src/__tests__/screen-reader-only-test.tsx, src/__tests__/touchable-test.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1387)
=> chore(tests): replace unit tests with harcoded classes

packages/generate-design-tokens/index.js
allow importing this kind of tokens:
https://github.com/Telefonica/mistica-design/blob/production/tokens/blau.json#L1145-L1163
=> chore(tokens): generate font size and line height tokens

src/spinner.css.ts, src/spinner.tsx
Jira issue: [Link](https://jira.tid.es/browse/WEB-1392) 
Explanation of the problem: https://stackoverflow.com/a/24626986
Before:
After:
=> fix(Spinner): remove extra space at the bottom of spinner

src/list.css.ts
Issue: https://jira.tid.es/browse/WEB-747
Cause of the problem: https://stackoverflow.com/a/40075917
=> fix(Row): fix missing hover in lists with href

src/list.tsx
Issue: https://jira.tid.es/browse/WEB-702
=> fix(row): add missing dataAttributes

src/list.css.ts, src/list.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1390)
Playroom snippet to check different behaviors: [Link](https://mistica-iecfwgw9e-tuentisre.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AFATjAbgSxgdwBUIIAbAZwAIB6APgB0A7RpAIQgA8KAHAQyimwMA5gE0AvMADMABgC%2B9BhQpIAkgxKCYFMrzAwxdEDzQQArgyiGKAM1MkSAdWxQALgAsKPDUIYqXMAFsyA3AYBn80QwUlJSQAYTcYMABrACMOCggGBJ5hfWAACkwASgoxGm0YFwBlFx5-AsN09hgoNUwYNDIYQwAaChL5RhiY7DI2FraGDq6exRikKgSktI4FYYXqmBIklw2Rkh5U7ZCCRICekH2YzC9TfKEq2vqYRpB3QMv%2Bw1hrHjs9iBirJrkoIFwXNgssFgABtUExYADO4weAUH4wP4AvoUfzsFxowwAEUx-xIgIosl6CKUSNuJHuhJAghm3RxeIJ6JA7U6bJAlOp8xGtORDNRXK8EQY9WwHXZMHxTIAguTOtLIXL%2BVSEQBdEFCmJZHJ5ABqKIkRRRpXKlRqdQahg%2BFxx9PuwOutA2izUGgYMAUiwmAaJsucnWo6wYSAASjAdNDZTAADI8ACeZhcyLQ2FyLgkjztLzeTq%2BXN%2BZMBwJsdkcznc0WUE24fAEwgkMiGBtU6k01fsTlcHh0PD0EgAjNI5A2RqwOK …
=> feat(Row,BoxedRow): add pressed style to list rows

src/community/blocks.tsx
Playroom snippet showing the issue: [Link](https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AFAThA5mmBnXAQgDYRgDWAOgHYAENALgJb1EwC8FITLMn1dACxgBDKIyqY2wYPzo0AbsKIBXGPBqcATAAYaAcQKcANLLr0YAD3rrO5q8dkBfR7IAOGbHlwoYaMDCp6KW0XWhpYXDA0RlcmCCoOEAiomLiqPioAegA%2BahAjLiEAWzwEAG0QYmFlfJAAeU0QAF0CgHdGKHoBXHKAZgA2bSbHIA)
=> fix(ProgressBlock): fix undefined check when progressPercent is 0

.github/workflows/ci.yml
Issue: [Link](https://jira.tid.es/browse/WEB-1411)
Context about the solution: [Link](https://github.com/orgs/community/discussions/25789#discussioncomment-3249273)
=> chore(ci): Cancel upload-failed-screenshots if workflow was cancelled

src/inline.css.ts
Issue: [Link](https://jira.tid.es/browse/WEB-816)
=> fix(Inline): avoid content overflow with wrap and negative space

src/__screenshot_tests__/form-fields-screenshot-test.tsx, src/date-time-field.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1488) (check comments in there for more context)
=> fix(DateTimeField): add default value for max

src/card.tsx, src/community/advanced-data-card.css.ts, src/community/advanced-data-card.tsx, src/form.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1496)
=> fix(AdvancedDataCard): fix hover on actions removing hover on card

src/text.tsx
https://teams.microsoft.com/l/message/19:68854aea147e4787803aff0e380e1208@thread.tacv2/1694099831941?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=e265fe99-929f-45d1-8154-699649674a40&parentMessageId=1693400997175&teamName=M%C3%ADstica&channelName=Help&createdTime=1694099831941&allowXTenantAccess=false
=> feat(Text): support textAlign right

src/button.css.ts, src/button.tsx, src/card.css.ts, src/tabs.css.ts, src/touchable.css.ts
Solving [this issue]( https://jira.tid.es/browse/WEB-1510) in Touchable instead of only in Tabs. In this way, we provide a more general fix to the problem.
=> fix(Touchable): add margin 0 as default to prevent Safari issues

src/fixed-footer-layout.css.ts, src/fixed-footer-layout.tsx
Issue: [link](https://jira.tid.es/browse/WEB-1548)
=> fix(FixedFooterLayout): prevent content from being rendered on top of the footer

src/snackbar.tsx
This was broken in https://github.com/Telefonica/mistica-web/pull/891
master:
https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AhArgFwxAdgMQEsAPGKPCCDGAJwBkBDATwkwB0cACDgI02xwC8wVH1wAFagQC29aow7jqMAM7KhACgCUHAQD4OwAL6HdAQTAYCuJAHp0WRdNmNdh9l2UxIOKM-v8hdy4OEQccAGUvXF85BRwJFTVgLR19IxNzS2s7UQion2ddILccIs4OcIgpGA5vKhwMDgALGhggpHCcejAAa25ZDmrVegBzGAFWEErqwcTRmpalSY4bMtt-XEISMgoqOiYWDDKQABoQDBahhABtEABZCAA3AmUMWRAAXTOAdwIoC%2BUNwAzAA2AAMJwA7CCABwnACMYIATAAWD6GIA
This branch:
https://mistica-ey0s5hf2x-tuentisre.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AhArgFwxAdgMQEsAPGKPCCDGAJwBkBDATwkwB0cACDgI02xwC8wVH1wAFagQC29aow7jqMAM7KhACgCUHAQD4OwAL6HdAQTAYCuJAHp0WRdNmNdh9l2UxIOKM-v8hdy4OEQccAGUvXF85BRwJFTVgLR19IxNzS2s7UQion2ddILccIs4OcIgpGA5vKhwMDgALGhggpHCcejAAa25ZDmrVegBzGAFWEErqwcTRmpal …
=> fix(Snackbar): z-index conflict with FixedFooterLayout

src/__screenshot_tests__/image-screenshot-test.tsx, src/__screenshot_tests__/video-screenshot-test.tsx, src/__stories__/image-story.tsx, src/__stories__/video-story.tsx, src/card.tsx, src/video.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1557)
=> fix(Video, DisplayMediaCard, PosterCard): show fallback on empty src

playroom/snippets.tsx, src/__stories__/dialog-story.tsx, src/__stories__/sheet-story.tsx, src/button.tsx, src/menu.tsx, src/touchable.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1561)
=> feat(Buttons, Touchable, Menu): accessibility improvements

src/button.css.ts
Issue: [Link](https://jira.tid.es/browse/WEB-1600)
=> fix(Buttons): fix active state not showing in mobile

playroom/components/index.tsx, playroom/preview-tools.css.ts
issue: [Link](https://jira.tid.es/browse/WEB-1635)
=> chore(PreviewTools): add animation to floating controls

src/callout.tsx, src/card.tsx, src/carousel.tsx, src/community/advanced-data-card.tsx, src/community/blocks.tsx, src/hero.tsx, src/image.css.ts, src/image.tsx, src/list.tsx, src/skeletons.tsx, src/stacking-group.tsx, src/video.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1647)
=> feat(Image, Video): use smallMedia token for border radius in some components

src/card.tsx, src/sheet.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1675)
=> fix(Sheet, Cards): prioritize dataAttributes component-name from parent element

doc/theme-config.md, src/theme.tsx
=> feat(ThemeContextProvider): Add support for Next14 Link component

src/accordion.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1620)
=> fix(Accordion): make component not responsive to changes in defaultValue

src/community/advanced-data-card.css.ts
=> fix(AdvancedDataCard): button margin

src/text.css.ts, src/text.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1696)
=> feat(Text): prioritize wrapping before breaking if word fits in container

src/__screenshot_tests__/progress-bar-screenshot-test.tsx, src/__stories__/loading-bar-story.tsx, src/__stories__/progress-bar-story.tsx, src/loading-bar.css.ts, src/loading-bar.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1707)
=> fix(LoadingBar): update broken animation

src/feedback.css.ts, src/feedback.tsx
Setting the background color for SuccessFeedbackScreen content will cause problems when using gradients
=> fix(SuccessFeedbackScreen): remove unnecesary background color

css/reset.css
Issue: [Link](https://jira.tid.es/browse/WEB-1754)
=> fix(CSS): prevent browser default behaviours when long pressing or dragging links

src/__tests__/form-test.tsx, src/form-context.tsx, src/form.tsx
https://jira.tid.es/browse/WEB-1770
=> fix(Form): remove error state when input is disabled

src/__tests__/select-test.tsx, src/select.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1746)
=> feat(Select): add default value

src/switch-component.css.ts, src/switch-component.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1624)
=> feat(Switch): add minimum interactive area in touchable devices

src/fixed-footer-layout.css.ts, src/fixed-footer-layout.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1825)
=> fix(FixedFooterLayout): remove background applied by elevation in desktop

src/community/advanced-data-card.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1830)
=> feat(AdvancedDataCard): add trackingEvent when card is interactive

src/snackbar.css.ts
Fix snackbar position in desktop according to specs
=> fix(Snackbar): Desktop position

playroom/preview-tools.css.ts
Issue: [Link](https://jira.tid.es/browse/WEB-1840)
=> fix(PreviewTools): update non working animation for floating case

src/accordion.tsx, src/card.tsx, src/carousel.tsx, src/community/advanced-data-card.tsx, src/feedback.tsx, src/loading-screen.tsx, src/sheet.tsx, src/slider.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1656)
=> feat(Accordion, Cards, Carousel, Feedback, Sheet, Slider): replace Array with ReadonlyArray in props

src/video.tsx
Issue: [link](https://jira.tid.es/browse/WEB-1846)
=> fix(Video): avoid duplicated state update in Video's state machine

src/community/blocks.tsx, src/progress-bar.tsx
=> feat(ProgressBlock): make progress bar hidden for screen readers

playroom/snippets.tsx, src/switch-component.css.ts
I took the opportunity to include new example screen snippets for Playroom
=> feat(Switch): Improve animation

src/counter.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1884)
=> fix(Counter): add aria-live to value

src/__tests__/snackbar-test.tsx, src/snackbar-context.tsx, src/snackbar.tsx
WEB-1889
related with: https://github.com/Telefonica/webview-bridge/pull/136
=> feat(Snackbar): buttonAccesibilityLabel

playroom/components/index.tsx, playroom/preview-tools.css.ts
Issue: [Link](https://jira.tid.es/browse/WEB-1924)
=> feat(PreviewTools): add forceTabs prop

src/index.tsx
=> feat(icon keywords): exported a list of keywords associsated with every mistica icon

.swcrc, package.json, src/screen-size-context-provider.tsx, src/theme-context-provider.tsx
Novum app no longer supports iOS 13: https://confluence.tid.es/display/CTO/%5BAPPS%5D+Novum+App+Information
=> feat(browser support): set min Safari version to 14

src/overscroll-color-context.tsx
=> fix(overscroll color): background color not changing when switching dark/light mode

src/callout.css.ts, src/callout.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1952)
=> feat(Callout): fix elements reading order and add role prop

src/chip.tsx
=> fix(Chip): missing data-component-name when closable 

src/feedback.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1843)
=> fix(FeedbackScreen): avoid double responsive margins in buttons when they are not fixed

src/snackbar-context.tsx, src/snackbar.tsx
=> fix(Snackbar): allow dataAttributes passed to openSnackbar

playroom/components/index.tsx, playroom/themes.tsx
current bug: https://mistica-web.vercel.app/playroom/#?code=N4Igxg9gJgpiBcIA8AFATjAbgSxgdwBUIIAbAZwAIALbWAPiQHp0tdDjy6AdAOyQCEIADwoAHAIZQo2HgHMAvMACMANgC%2B3HhQpIAglEzieYGFAAi4gC7iAwuLRRe27ZeyWSMeVxCAyQAoBlGBIAM1wKAHESCAAjCFEScQBPCgBmAAZw-m8nZ1d3GF0yLxAqACZvCkYAKgCYWQBXbDQKcQoYMlEYMGxQsHEAc4BjiApYCl0TMjJsaOwSWkkYCirGHO0YIUs0cUUAbTXnVDQIWQwp-iiwAGsD52oYSRkFYGBbu4pDEnqYeApvJQArBEsiAADRvO6WDaWX7eaQdCA8AC3mBg2EoY3SwO84K0720ajUELEx1O7TIKBgaBMPEsigBaSJeLujDouLuAF0mXdxGBXIiisB9sznK8RXcAJKQHi-KWIgCyD0s0XEJBIADE5h4oOz8RRESwpr8ABQASgo8joFGAal1%2BIS0SCsJAip49Rxb1tBy5B2CxChaAlAFtxLJPMAkMHQ0syNTilRLJZRGR4IxViB7thZAnFAAWRmVOjc5x%2BiABgjQ4qRGJxBKJbIiqgYYLFADEDe0rN4TEEQk0YJAlioMCD7QQuxAADVsJgIAB9ABy%2BBAHNBIDwtCHZHHKRUaVXg7cHgQIH0hmMpgoFmsFDsDkY-ieHhJ0HqfJAaiAA
=> chore(PreviewTools): Fix skin mapping

src/logo.tsx
=> fix(Logo): fix webpackChunkName magic comments

playroom/components/index.tsx, playroom/use-scope.tsx
https://jira.tid.es/browse/WEB-2031
The text tokens playroom example needs some small changes to work:
https://mistica-3sea1bzzr-flows-projects-65bb050e.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8UCWA3AOgOwAS4GcAXATwBsYBeYYHffAIwEMwBrAcwCcIBXbKeLkhkInAgDpmbLr34BhCNiJNU2GJwA0deg1GxOAGRgAzIoMwgAjAAcAHoQhlUUC1rw696hSM6DhoiTR0Z3U3bXxrCAJUIlRFcxBjVFsYFxA3elxOVHYACzNcAAYM%2BgB3ZyJchIAmAGZCu1dw3FyYHPyEy0LC9Fym9wBfAZwAPm0kACEIe2smKDRsdgANaksANgHcWfnVdgBNVY2x93wkAGVlNkJZsCpgdYHjzNOAFRiKSxGDCDAmCiQAPRvIgfJ7PJAAJTmcQA4tweNZmplsEwALZUCwAKx4qDAJAAtMZODiiBYkfQmNkmPiyEwGDAyBQoAwSJQLLT6WQySdnrBjEweGQiAA1P48O7sGBEC5MIgwAAU7J%2BfxgFgAlLgAPya3AWGAEfEAUTOFmGPMyijkuSYizuBClMrlipAIl%2BFHVZueuDBXvOl1Y1xYdwePq9uEh0IgEx4RCIilw6DFGJA%2BqNJpAI1Txtw8rOs1UasBULQUZjcewod9xbi0dj8cTZHFbJA1iI%2BImEIsI1b7YhOYmnCYAC9UGRCwDq …
=> chore(Playroom): fix PreviewTools tabs icons and alert/dialog/confirm

doc/texts.md, doc/theme-config.md, src/__acceptance_tests__/input-fields-acceptance-test.tsx, src/__stories__/credit-card-expiration-field-story.tsx, src/__stories__/credit-card-number-field-story.tsx, src/__stories__/cvv-field-story.tsx, src/__stories__/date-field-story.tsx, src/__stories__/date-time-field-story.tsx, src/__stories__/decimal-field-story.tsx, src/__stories__/email-field-story.tsx, src/__stories__/iban-field-story.tsx, src/__stories__/integer-field-story.tsx, src/__stories__/month-field-story.tsx, src/__stories__/password-field-story.tsx, src/__stories__/phone-number-field-story.tsx, src/__stories__/search-field-story.tsx, src/__stories__/text-field-story.tsx, src/text-field-base.tsx, src/theme-context-provider.tsx, src/theme.tsx
=> feat(Form fields): allow blocking copy/cut

playroom/components/animation.tsx, playroom/components/index.tsx, playroom/snippets.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1712)
=> chore(Playroom): add support for using Lottie animations

src/__stories__/use-element-dimensions-story.tsx
Changed backgroundColor: "grey" to backgroundColor: "red" as specified in Title
=> chore(Storybook): Fix typo in use-element-dimensions story

src/accordion.css.ts, src/accordion.tsx, src/boxed.css.ts, src/boxed.tsx, src/card.css.ts, src/card.tsx, src/list.css.ts, src/list.tsx, src/touchable.css.ts
WEB-2157
[OBVIVO-2900](https://jira.tid.es/browse/OBVIVO-2900)
=> fix(Row/Cards): browser focus ring in boxed components

src/snackbar-context.tsx, src/snackbar-native.ts, src/snackbar.tsx
=> feat(Snackbar): dont lazy load snackbar when using webview bridge

css/mistica-common.css, examples/css/index.html
WEB-2180
Take into account changes in https://github.com/Telefonica/mistica-web/pull/1343
=> feat(mistica-css): TextLink

src/text-field-components.tsx, src/text.tsx
WEB-2132
https://teams.microsoft.com/l/message/19:68854aea147e4787803aff0e380e1208@thread.tacv2/1736187365791?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=e265fe99-929f-45d1-8154-699649674a40&parentMessageId=1736187365791&teamName=M%C3%ADstica&channelName=Help&createdTime=1736187365791
=> feat(TextField): make field error aria-live

src/text-field-base.tsx
=> fix(TextField): make prefix hidden to screen readers

src/image.css.ts, src/image.tsx
=> feat(Slideshow): allow images with border radius inside

css/mistica-common.css, examples/css/index.html
=> feat(mistica-css): checkbox

playroom/snippets.tsx, src/__stories__/funnel-navigation-bar-story.tsx, src/__stories__/main-navigation-bar-story.tsx
Try to cover a repeated doubt from different teams with this topic: Can I change logo to other one in navigation bars?
=> chore(Storybook): include customLogo control in mainNavigationBar and FunnelNavigationBarStory

css/mistica-common.css, examples/css/index.html, examples/css/main.js
https://jira.tid.es/browse/WEB-2196
=> feat(mistica-css): slider

src/form.tsx, src/menu.tsx, src/select.tsx
=> feat(Form, Select, MenuItem): support dataAttributes

css/mistica-common.css, examples/css/index.html, examples/css/style.css
=> feat(mistica-css): padding, stack, inline, align

src/__stories__/progress-bar-story.tsx, src/progress-bar.tsx
=> fix(ProgressBar, ProgressBarStepped): fix screen reader anouncement

src/__tests__/callout-test.tsx, src/callout.tsx
=> feat(Callout): allow setting title aria-label

playroom/frame-component.tsx, src/dialog-context.tsx, src/dialog.tsx, src/sheet-root.tsx
https://jira.tid.es/browse/WEB-2258
=> feat(Modal,Sheet): move focus to the element that triggered the modal when it closes

src/button.tsx, src/card.tsx, src/drawer.tsx, src/icon-button.tsx, src/list.tsx, src/touchable.tsx
=> feat(Touchable components): add support for aria-description, aria-describedby, aria-labelledby and aria-current

src/stepper.css.ts, src/stepper.tsx, src/text-tokens.tsx
WEB-2166
https://www.figma.com/design/YIQIeK0R4bQNNkw2Friv6b/%F0%9F%94%B8-Stepper-Component-Specs?m=auto&node-id=1876-781&t=JtsFc0x2F8qis1w2-1
https://www.w3.org/WAI/tutorials/forms/multi-page/#using-step-by-step-indicator
https://github.com/user-attachments/assets/30be0ace-e1f3-4392-9071-991b6b29819b
=> fix(Stepper): improve a11y

src/select.css.ts, src/text-field-components.css.ts
https://jira.tid.es/browse/WEB-2263
Can be verified in [this playroom](https://mistica-5evqcrz1v-flows-projects-65bb050e.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gBGANgF8A%2BAHWM0yQGUAXXMAa0wBnPGBiVajFmzaoArly4RiABQBOhALa5VAT0xK1MQYMoAKAJSZyDTMDqMAwgBtC-TBphIA9CnmKV6lq6zMRS0pwwTjBgXGHSmMS4XIQAbjBx0oke5EwgAGaqsoRcgrkZbE64AEaROSAOABYQEIIwmLiYBUWxIOX62MlKJsAA2n1swJgpuE6yMPCYuRCquGTpIAA0mFww6FwLuQDyK2u5mHQb47ZTM3MHIFWrT7lbO3v3KE%2BJZxd9ALp0DJeEIyLzcXh8ELeNDoEKbEBcBowDyCBAjEAAWQgKUIgh4qhAfw2IAA7oQoIjUfARgBmGgABgBQA)
=> fix(Select): Show native select focus ring

src/__tests__/spinner-test.tsx, src/spinner.tsx
WEB-2245
https://github.com/user-attachments/assets/dfdf30c3-3b2e-44bc-aae4-33a6adab28e2
https://github.com/user-attachments/assets/df9b4740-424b-46c7-8378-0cc5a6c9559c
=> fix(Spinner): improve aria-live a11y

package.json
=> feat(package.json): remove node version restriction

src/fixed-footer-layout.tsx
WEB-2308
Replaced the `<aside>` with a plain `<div>` and allow customizing the footer role
=> feat(FixedFooterLayout): allow custimizing footer role

src/community/advanced-data-card.tsx
=> fix(AdvancedDataCard): wrong voiceover behavior in touchable cards with extra 
