flow-defs/text.js.flow, size-stats.json, src/text.tsx
jira: WEB-245 
bug:
https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8BhAFjMBrARhAHgAQB2AhgLYwC8AOuBtnvnYRMeqcQObXADOMAC4BlQaUEwAFHQCWfACJsYdAJQBfAHw1ihQkgAqMfIIBMhCcfmYIAJ3Ey2VYDxFiJ0kHMXFlIFYQB%2BQjoAGxkfAFpBNBsIAFcuNBZ4QjjiWAAzcJgoTW1dXT4ISnNoCHy9AHpDYxMtYiRK9ExcAnqQABoQaJhKPgQAbRAAWQgANzkxGxAAXS6AdxkoaP74AYBGAAYTABYZtSA
fixed:
https://mistica-web-f78ukeztn-atabel.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8BhAFjMBrARhAHgAQB2AhgLYwC8AOuBtnvnYRMeqcQObXADOMAC4BlQaUEwAFHQCWfACJsYdAJQBfAHw1ihQkgAqMfIIBMhCcfmYIAJ3Ey2VYDxFiJ0kHMXFlIFYQB%2BQjoAGxkfAFpBNBsIAFcuNBZ4QjjiWAAzcJgoTW1dXT4ISnNoCHy9AHpDYxMtYiRK9ExcAnqQABoQaJhKPgQAbRAAWQgANzkxGxAAXS6AdxkoaP74AYBmEwAGGbUgA
=> fix(Text): reset textDecoration when switching back to undefined

playroom/components.tsx
Controls theme was not forced to light, this fixes it.
Verified on Mac safari, using dark/light modes
=> chore(PreviewTools): Set controls theme to light

flow-defs/box.js.flow, flow-defs/boxed.js.flow, flow-defs/button.js.flow, flow-defs/icon-button.js.flow, flow-defs/select.js.flow, flow-defs/text-field-base.js.flow, flow-defs/text-link.js.flow, flow-defs/touchable.js.flow, flow-defs/utils/dom.js.flow, size-stats.json, src/__tests__/form-test.tsx, src/__tests__/touchable-test.tsx, src/box.tsx, src/boxed.tsx, src/button.tsx, src/dialog.tsx, src/icon-button.tsx, src/select.tsx, src/text-field-base.tsx, src/text-link.tsx, src/tooltip.tsx, src/touchable.tsx, src/utils/dom.tsx
instead of defining `data-whatever` props in our components, we want to use a dictionary `dataProperties` to be able to pass any `data attribute` to the component
=> WEB-271 migrate to dataAttributes

flow-defs/integer-field.js.flow, size-stats.json, src/__acceptance_tests__/form-fields-acceptance-test.tsx, src/credit-card-number-field.tsx, src/cvv-field.tsx, src/decimal-field.tsx, src/integer-field.tsx
related to #191 
Applied to CreditCardInput and DecimalInput (used by CvvField). Not applied to CreditCardExpirationField since it provokes more problems than what it solves...
**before**
**after**
=> feat(FormFields): use rifm to format CreditCard and Decimal fields

flow-defs/theme.js.flow, flow-defs/utils/media-queries.js.flow, playroom/components.tsx, size-stats.json, src/list.tsx, src/navigation-bar.tsx, src/password-field.tsx, src/select.tsx, src/tabs.tsx, src/text-link.tsx, src/theme-context-provider.tsx, src/theme.tsx, src/utils/media-queries.tsx
I've extracted the `@media (pointer: fine), (pointer: none)` media query that we used in some components to apply hover styles to a common place and exposed it in theme context.
Applied the media query to some componente where we weren't using it, like `Tabs`
=> feat(mq.suportsHover): include mq for devices that support hover

src/feedback.tsx
Now Vivo's info and error feedback screens will use the same icons as the others.
=> feat(Feedback): show info/error icons in vivo

src/form.tsx
Because when creating custom inputs (from TextFieldBase), even if you use a custom validator function, the default validation (the one that happens when input is required and is value in not empty) take place. In new inputs chips the actual input value could be an empty string, because the real value (and array of string) will live in the form's state. 
So, instead of reading the reading the current input value, real the value that lives in the form state (that is the one that will also be used in onSubmit)
=> fix(Form fields): use rawValue to check if a form field is empty

src/popover.tsx
When the user clicks on the close icon, the popover closes but the underlying component, if it is touchable, gets actionated too.
Here you can see a `Popover` over the `AgreementSelector`, and when I close the popover, the agreement selector gets actionated too:
https://user-images.githubusercontent.com/4521712/154485133-a3c8096a-eda8-4b93-9df6-eb757588bbe9.mp4
=> fix(Popover): bug with close event propagation

src/carousel.tsx
this same [fix](https://github.com/Telefonica/mistica-web/pull/430#discussion_r816005422) but applied to `Slideshow` too
=> fix(Slideshow): scroll snap stop on android

flow-defs/theme.js.flow, src/theme.tsx
without this change, I have this kind of errors in flow:
This is the explanation of the error:
https://flow.org/en/docs/faq/#toc-why-can-t-i-pass-a-string-to-a-function-that-takes-a-string-number
=> fix(types): make skin in ThemeConfig readonly

flow-defs/image.js.flow, flow-defs/video.js.flow, src/image.tsx, src/video.tsx
[TGT-777 ](https://jira.tid.es/browse/TGT-777)
=> feat(Image,Video): use original proportion when setting `aspetRatio={0}`

src/text.tsx
In a recent change in Text to fix a word break bug in old browsers, we set the wordBreak style to `'normal'` when the prop was not specified explicitly. But we had some code in webapp that relied in the old behavior of inheriting wordBreak style from parent dom elements. This PR reverts that to the previous behavior.
More info in this thread: https://teams.microsoft.com/l/message/19:4fc0c9a0eec140e3befc341e7271e9c2@thread.skype/1655215140563?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=bef9be07-03e4-4afb-8a79-f720a63e4c28&parentMessageId=1655215140563&teamName=Novum&channelName=Checkout-QSys&createdTime=1655215140563
Webapp code relying on style cascade:
https://github.com/Telefonica/webapp/blob/master/web/src/pages/payment-barcode/components/pay-now.js#L113-L117
The right fix …
=> fix(Text): inherit word-break style from parent when the wordBreak prop is not set

src/checkbox.tsx
https://user-images.githubusercontent.com/6722153/186265151-24a70077-0b16-4fed-89b3-9c460ded06b5.mov
When you enable and disable the checkbox a junk pixel appears
Apparently only in chrome
https://stackoverflow.com/questions/9983520/webkit-animation-is-leaving-junk-pixels-behind-on-the-screen
=> fix(Checkbox): fix junk pixel in checkbox

src/skins/blau.tsx, src/skins/telefonica.tsx
https://github.com/Telefonica/mistica-design/issues/681
There is not exist test for dark mode colors, should be?
=> fix(Skin): improve control constant in dark mode in Blau & Telefónica

playroom/components.tsx
=> fix(playroom): PreviewTools tabs in desktop

scripts/compile.js
with the introduction of vite we lost support for old browsers
As a consequence, webapp build fails because we have an ES version check
This fix uses swc to transpile vite output
=> fix(build): use browserslist as compilation target

src/hooks.tsx, src/theme-context-provider.tsx, src/theme.tsx
We was trying to use `React.useId` conditionally to support React 17 and 18, but this doesn't seem to work:
This is a workaround that will allow mistica to work in React 17. React 18 users can inject `useId` if they prefer to use it instead of the builtin solution:
`<ThemeContextProvider theme={{...restOfTheTheme, useId: React.useId}}>`
=> fix(useId): support React 17

.github/workflows/ci.yml, src/__screenshot_tests__/carousel-screenshot-test.tsx, src/__screenshot_tests__/hero-screenshot-test.tsx, src/__screenshot_tests__/highlighted-card-screenshot-test.tsx, src/__screenshot_tests__/image-screenshot-test.tsx, src/__screenshot_tests__/inline-screenshot-test.tsx, src/__screenshot_tests__/media-card-screenshot-test.tsx, src/__screenshot_tests__/video-screenshot-test.tsx, src/test-utils/index.tsx
Since the last week, we have unstable screenshot tests in CI. All the tests pass in local but there are rendering diferences in images in CI, we suspect it's due to some change in GitHub hosted runners, but it's weird because we run the tests inside a docker image.
This pr is a contingency solution to make those tests pass and unblock the CI pipeline
=> chore(CI): fix unstable acceptance tests in CI

src/card.tsx, src/highlighted-card.tsx
As discussed in [this issue](https://github.com/Telefonica/mistica-design/issues/932), adding `hypen="auto"` to every text field for every card:
- Data
- Display Data
- Display Media
- Highlighted
- Media
- Poster
- Snap
=> feat(Card): add hypenation to all cards

jest.unit.config.js, src/__tests__/button-test.tsx, src/date-time-picker.tsx
Fixes the following warning:
```text
- warn ./node_modules/@telefonica/mistica/dist/date-time-picker.js
Critical dependency: the request of a dependency is an expression
Import trace for requested module:
./node_modules/@telefonica/mistica/dist/date-time-picker.js
./node_modules/@telefonica/mistica/dist/date-field.js
./node_modules/@telefonica/mistica/dist/index.js
./app/page.tsx
```
Verified using the `hello-world-web` application. Copying the dist folder of the fixed mistica (and deleting `.next/cache`), this warning dissapears.
=> fix(DateTimePicker): fix locale imports in date-time-picker

playroom/components/index.tsx, playroom/preview-tools.css.ts
PreviewTools renders a border at the bottom of the tabs. After merging changes in Tabs, this border was not looking good in desktop:
=> chore(PreviewTools): update height in desktop to avoid double border at bottom

src/button.tsx
When we deprecated aligned prop in ButtonLink, we removed its logic from the component. This should be done during next major release, not now, so this PR introduces it back temporarily
=> fix(ButtonLink): add aligned prop back until next major release

src/index.tsx
This workarounds issues with next12 and commonjs modules. Components imported from from community.js are not able to access the Theme context, and community.js internally uses ES imports which causes problems in next build.
Consider this a temporary workaround that will be removed in the next mistica major.
=> fix(Community): export community components with namespace

src/__stories__/image-story.tsx, src/tabs.css.ts
In Safari, buttons have extra padding/margin by default ([stack overflow post](https://stackoverflow.com/questions/5170041/button-extra-padding-problem-in-safari)). We need to remove this for tabs.
Issue: [Link](https://jira.tid.es/browse/WEB-1510)
=> fix(Tabs): remove extra margin in safari

src/form.tsx
Solving issue reported [here](https://github.com/Telefonica/mistica-web/issues/842).
When using React with StrictMode on, in dev environment components' effects are executed twice (https://react.dev/reference/react/StrictMode#strictmode)
After mounting the component and executing the effects once, the `isMountedRef` value is set to false, but it's never reset to true in the second time the effect is triggered. This causes the form to never update its state to "filling" after performing a form submit:
=> fix(Form): set mountedRef value to true on client side first render

src/__acceptance_tests__/__ssr_pages__/text.tsx, src/__acceptance_tests__/text-ssr-acceptance-test.tsx, src/text.tsx
The empty string in conditional values inside `assignInlineVars` produced different styles in server and client
=> WEB-1430 fix Text SSR

src/__screenshot_tests__/stacking-group-screenshot-test.tsx, src/header.tsx
This was broken because of this change:
https://github.com/Telefonica/mistica-web/pull/880/files#diff-e751a29b3f34d283e9d54e96a51d36af37fbbaa38f8fdb994b3e5fa920065ea2
This causes this issue in webapp:
=> fix(Header): don't render title when not provided

css/reset.css, src/text.css.ts
https://jira.tid.es/browse/WEB-1578
=> fix(reset.css): avoid iOS Safari to unexpectedly zoom some font sizes

src/accordion.tsx, src/loading-bar.tsx, src/menu.tsx, src/navigation-bar.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1622)
Using timeout for Transition/CSSTransition components in acceptance testing was causing some tests to fail ([Teams thread describing the issue](https://teams.microsoft.com/_?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10#/conversations/unknown?threadId=19:be8725e15a8c4cc5ae1bf5d67fad4b7f@thread.skype&messageId=1699433116118&replyChainId=1699433116118&ctx=channel)).
By setting timeout to 0 in acceptance tests, the failing tests are fixed:
=> fix(Menu, Accordion, LoadingBar, NavigationBar): disable react transition group timeout for screenshot tests

src/__tests__/nestable-context-test.tsx, src/index.tsx, src/nestable-context.tsx, src/overscroll-color-context.tsx
jira: https://jira.tid.es/browse/WEB-1632
Webapp uses nestable-context for navbar state.
There is an special attribute in navbar state called `resetToDefaultState` that is used to reset the state of the navbar. 
https://github.com/Telefonica/webview-bridge/blob/master/src/utils.ts#L106-L110
When that attribute is used, the merging logic should be different. Something like this:
=> feat(createNestableContext): allow custom valuesReducer

src/carousel.tsx
context: https://teams.microsoft.com/l/message/19:be8725e15a8c4cc5ae1bf5d67fad4b7f@thread.skype/1699986429590?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=bef9be07-03e4-4afb-8a79-f720a63e4c28&parentMessageId=1696319756336&teamName=Novum&channelName=webapp-dev&createdTime=1699986429590
related issue: https://github.com/reactjs/react-transition-group/issues/382#issuecomment-455539373
and a list of dom methods that cause reflow: https://gist.github.com/paulirish/5d52fb081b3570c81e3a
=> fix(Carousel): avoid immediate style reflow on component mount

src/__tests__/hooks-test.tsx, src/hooks.tsx
The main issue was that the hook state wasn't shared between different hook instances. Extracting the state to module variables fixed the issue.
The issue was reproduced on creating multiple Overlays with scroll disabled: one for the menu, another for the modal.
Added some unit tests to cover those scenarios
=> fix(useDisableBodyScroll): fix nested usage

src/__screenshot_tests__/inline-screenshot-test.tsx
Skipping unstable test until we investigate it: https://jira.tid.es/browse/WEB-1648
=> chore(Inline): skip unstable test

src/community/blocks.tsx
The motivation of this is to be able to pass API received values (typed as read only) to the component without a cast, spread or any other conversion to mutable array.
[WEB-1654](https://jira.tid.es/browse/WEB-1654)
=> fix(Blocks): Set array props as read only

src/hooks.tsx, src/tooltip.tsx
Some of the tooltip screenshot tests were failing randomly. The cause was the tooltip's width changing for some reason that we couldn't explain. Given that the component was not reactive to these changes, the tooltip ended up misaligned after the width changed.
In this PR, we force the tooltip to recompute its position when it's width/height changes, and therefore fixing the issue.
=> fix(Tooltip): make component reactive to changes in tooltip content

src/__tests__/overlay-test.tsx, src/overlay.tsx
WEB-1663
Playroom code to verify:
```
N4Igxg9gJgpiBcIA8AVCBXMALAhgIwBsYAdAOwAJyJSAFAJxgGdGBeYACgEpyWA%2BcnEToAXdsHIBbJoxwBzGPHLEQGYYwCWsZeQC%2BnHWUqNhATyJtxeCHVh1FygIwAHAB7lGEApvIMo2nQakvIbkSABCEG5OOFBQ6qSybA4AbDrBFJShALIwpOghmT65tig4dPLCbGJFAGYANFS0DMwN6ow5eQDyTrm63Hzk7AWFoWHowsLU9OoSZSbDI7VsDDWBi4VTzawcMP38wAvrMAB0xhBO9OdyOMLq1FwA3IeLm9KPz5kBH0am5sDisxcAHVNMIsPYQDV1MIALSQUjCXLCfxrdbpdaZYBtDrobq9AD8ShAAGECBBGCQQOQIXjSMpUYskAB6MYTTYzObokb6Q4MUi2HFVcQrBpgAg4ZgAORwUj6PH4QwyjLiADclsAVjpyGKJYxpVI2DqpTKYGlvtlcugAJKIiTmyjivAwAgsZTnW7UcgOZT2xr0aRVPYCISiAHSOQKIlSPJUJweulUvQM9ZMrmMpmqtOZHlK8ipkLMiIudLMtCYXCEGDpEB1EBgmBSRgIADaICyEBVbWEZRAAF1awB3UFYJvwZsOADMyQAHL2dEA
```
=> fix(Overlay): stop event propagation on click

src/inline.css.ts
https://jira.tid.es/browse/WEB-1669
In global ecommerce, we have a list of checkboxes. Sometimes, when the user clicks on one, the below one is activated instead. This is caused by the clickable area of the checkbox:
The issue is caused by Inline margins:
The simpler fix I could think of is removing pointer-events from `Inline` parent `div`. I can't think of a case where this could be problematic. After this fix, the clickable area is the one of the `Checkbox` parent `div`, not the `Inline` children:
A simpler/elegant fix would be stop using margins and use flex gap in `Inline`, but we can't use it yet:
grid gap has better support, but not enough:
=> fix(Checkbox): wrong clickable area

src/text-field-base.css.ts
=> fix(InputFields): Align text to the left in date/time input fields. In iOS they are centered by default.

src/__stories__/video-story.tsx, src/video.tsx
WEB-1713
After releasing this fix, the following change is required in webapp
```diff
$ git diff
diff --git a/web/src/explore/hooks/use-card-media-element.tsx b/web/src/explore/hooks/use-card-media-element.tsx
index 2ef3e7a5da..c3b2ec6892 100644
--- a/web/src/explore/hooks/use-card-media-element.tsx
+++ b/web/src/explore/hooks/use-card-media-element.tsx
@@ -54,7 +54,7 @@ export const useCardMediaElement = ({
onExit: (ref) => {
// Should reset and display the poster image
if (!isRunningAcceptanceTest()) {
-                ref?.load();
+                ref?.stop();
}
},
threshold: 0.25,
```
=> feat(Video): `stop` method. To stop video and show the poster (if available)

src/__stories__/image-story.tsx, src/image.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1802)
Context: [Teams thread](https://teams.microsoft.com/l/message/19:be8725e15a8c4cc5ae1bf5d67fad4b7f@thread.skype/1711548515702?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=bef9be07-03e4-4afb-8a79-f720a63e4c28&parentMessageId=1711548515702&teamName=Novum&channelName=WebCore-public&createdTime=1711548515702&allowXTenantAccess=false)
This PR also solves a similar issue [reported in Github](https://github.com/Telefonica/mistica-web/issues/1028)
=> fix(Image): reset error state when src changes

src/cvv-field.tsx, src/icon-button.tsx
When we removed deprecated iconButton usages in Mistica, CvvField was accidentally skipped.
=> feat(IconButton): update usage in CvvField and remove baseIconButton

src/accordion.tsx, src/callout.tsx, src/card.tsx, src/empty-state-card.tsx, src/empty-state.tsx, src/header.tsx, src/hero.tsx, src/highlighted-card.tsx, src/list.tsx, src/navigation-bar.tsx
WEB-1796 
I've intentionally not made it configurable in some components:
- Full screen components like feedback screen: because there shouldn't be any reason to not use `<h1>` there
- Some components like tooltip/popover. I think it's fine to always render a simple `<span>` in those cases
=> feat(Accordion,Callout,Cards,EmptyState,Header,Hero,Row,NavigationBar): added titleAs prop to allow configuring heading level

src/__tests__/list-test.tsx, src/inline.tsx, src/list.tsx
WEB-1719
`RowList` and `BoxedRowList` will have `role="list"` by default, and the children `Row`/`BoxedRow` elements will have the `role="listitem"` by default.
`Inline` will allow to setup `role="list"` and their children will have the `role="listitem` set automatically, as we were [already doing with `Stack`](https://github.com/Telefonica/mistica-web/blob/master/src/stack.tsx#L64)
Playroom to test the PR with a screen reader:
https://mistica-hxdstsm8w-tuentisre.vercel.app/playroom/preview/#?code=N4Igxg9gJgpiBcIA8AlCB3AMgSwM4BcA+AHQDsACc1Dc-bfAGxgF5iQAVept82XMAE7YADnQilWIACIx+Q0dnE9xABQGzczYAAoAlOWaFywAL4nyAehIUqadLS4s2nRjHIAmHn0EixEtjJyvooUniDkquq4mjr6hsZmltZIFnY4BNZkSABCEAAeMFBpeERklDn5hXYOrpIu3OHe8n6SgT4KSuGRGlp6Bkam5lZlVLkFRTR0tc6OHl6y7S0BC80hc12kaj2x-QlDyRZjVRjppaRZABIQQgBe4vgAhgwAyo …
=> feat(RowList, BoxedRowList, Inline): support list a11y role

src/list.tsx
Issue found when updating mistica in Novum webapp:
This is caused because they are wrapping rows with a flex div
=> fix(Row): not having full width in some cases

src/image.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1804)
=> fix(Image): prevent loading skeleton from using default border radius value

src/utils/__tests__/browser-test.tsx, src/utils/browser.tsx
This will make easier to test redirects in unit tests
=> fix(utils): use `location.assign` to redirect, instead of `location.href`

src/theme-context-provider.tsx
This is useful in some special cases where we don't need the injected styles with the skin design tokens.
For example, Novum webapp has a node entrypoint that SSR mistica icons, we don't want the generated svg to contain the theme styles
=> feat(ThemeContextProvider): withoutStyles prop, to avoid injecting styles

src/__acceptance_tests__/__ssr_pages__/main-navigation-bar-large.tsx, src/__acceptance_tests__/__ssr_pages__/main-navigation-bar.tsx, src/icon-button.css.ts, src/tooltip.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1879)
=> fix(IconButton): add borderRadius to button's overlay

src/__type_tests__/card-type-test.tsx, src/card.tsx, src/community/advanced-data-card.tsx
=> feat(Cards): add role prop for touchable cards

src/__tests__/table-test.tsx, src/table.css.ts
When executing an unit test we don't have a viewport, so media queries are not valid there. This was causing row actions to be rendered twice when using collapsed-rows mode
=> fix(Table): avoid rendering row actions twice in jsdom

src/__tests__/select-test.tsx, src/select.tsx
WEB-1953 WEB-1954
We want to support the case of a Select without a selected initial option. To support this we are including an additional default empty `<option>` in the `<select>`.
We style this empty option with `display: none` to avoid this option to appear in the select list when we open it. This works as expected in Chrome:
But it doesn't work as expected in Safari, and the empty option is shown when the select is open:
The best fix I've found is using the select's label for that empty option:
And once one of the options is selected, we remove the empty one. So, if we open the select again, the empty option isn't shown anymore (like in Chrome):
=> fix(Select): onChange was called twice and there was an empty option in iOS

src/__tests__/callout-test.tsx, src/__tests__/chip-test.tsx, src/__tests__/data-card-test.tsx, src/__tests__/dialog-test.tsx, src/__tests__/display-data-card-test.tsx, src/__tests__/display-media-card-test.tsx, src/__tests__/media-card-test.tsx, src/__tests__/naked-card-test.tsx, src/__tests__/popover-test.tsx, src/__tests__/poster-card-test.tsx, src/__tests__/snackbar-test.tsx, src/callout.tsx, src/card.tsx, src/chip.tsx, src/dialog.tsx, src/popover.tsx, src/snackbar.tsx, src/tooltip.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-1966)
=> feat(Popover, Snackbar, Callout, Chip, Dialog, Cards): allow customizable close button label

src/text.tsx
=> fix(Vivinho char): vivinho char in headings being read as a separated heading

src/__tests__/navigation-breadcrumbs-test.tsx, src/navigation-breadcrumbs.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-2006)
=> feat(NavigationBreadcrumbs): allow executing onNavigate when pressing a link

src/__tests__/phone-number-field-test.tsx, src/phone-number-field.tsx, src/test-utils/ssr.tsx, src/text-field-base.tsx
* load libphonenumber on demand
* allow custom formatter which allows to not use libphonenumber at all
=> feat(PhoneNumberField): Custom formatter support + lazy load libphonenumber on demand

src/__acceptance_tests__/input-fields-acceptance-test.tsx, src/__screenshot_tests__/input-fields-screenshot-test.tsx, src/__tests__/phone-number-field-test.tsx, src/phone-number-field.tsx, src/test-utils/ssr.tsx, src/text-field-base.tsx
Reverts Telefonica/mistica-web#1244 because several issues have been detected
=> fix(PhoneNumberField): Revert lazy load of libphonenumber

.storybook/preview.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-2064)
=> chore(Storybook): fix theme default values for stories opened in a new tab

.storybook/storybook-manager-theme.js
Top bar controls was not using the correct brand color for each brand
Before
After
=> chore(Storybook): fix hover color in top bar controls

src/__stories__/custom-field-story.tsx, src/card.css.ts, src/card.tsx, src/chip.css.ts, src/chip.tsx, src/community/advanced-data-card.css.ts, src/community/advanced-data-card.tsx, src/hero.tsx, src/list.css.ts, src/list.tsx, src/menu.css.ts, src/menu.tsx, src/tag.css.ts, src/tag.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-2072)
Verified that no tests in webapp are failing after these changes :heavy_check_mark:
=> feat(Box): remove className usages

src/__tests__/list-test.tsx, src/list.tsx, src/screen-reader-only.css.ts, src/screen-reader-only.tsx
https://jira.tid.es/browse/WEB-2061
By default, the browser will read text content inside rows one by one (title, description, etc).
With the changes in this PR, if an aria-label is provided to the informative row, the whole row will be read as a single text (the one provided in the aria-label prop) 
This PR also fixes https://jira.tid.es/browse/WEB-1885 which is a basically revert of https://github.com/Telefonica/mistica-web/pull/942. As part of this PR we allow passing custom styles (via `className` prop) to `ScreenReaderOnly` to workaround possible style issues found (like the one described originally in https://github.com/Telefonica/mistica-web/pull/942).
=> feat(Row): allow aria-label in informative rows

src/__tests__/hooks-test.tsx, src/hooks.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-2088)
=> fix(useDisableBodyScroll): avoid affecting body's height

src/__tests__/mosaic-test.tsx, src/mosaic.tsx
Issue: [Link](https://jira.tid.es/browse/WEB-2092)
=> feat(HorizontalMosaic, VerticalMosaic): allow passing gridMode information to each item

src/__tests__/form-test.tsx, src/form.tsx, src/utils/platform.tsx
Fields that are excluded from autofocus on error in iOS because the focus action opens the picker/selector
* date
* datetime-local
* month
* select
Note: scroll to element not affected
A simple unit test that covers these scenarios has been added but you can be manually test this using playroom with a snippet like:
```jsx
<Form>
<Stack space={16}>
<Select
name="field"
label="field"
options={[{ value: "x", text: "x" }]}
/>
<ButtonPrimary submit>Submit</ButtonPrimary>
</Stack>
</Form>
```
and opening the preview in an iphone
=> feat(Form): Disable autofocus on error for some fields on iOS

src/drawer.css.ts
screenshot reported by Vivo devs:
=> fix(Drawer): missing css value for transform

src/touchable.tsx
WEB-2149
Adding minimal support just to the Touchable component. Further implementations of the prop in components built on top of Touchable is left to a later PR (cc/ @wyunreal).
Playroom demo: 
https://github.com/user-attachments/assets/b04f4153-14f4-4fc0-9c94-1004ff379863
=> feat(Touchable): add aria-current support

src/list.tsx
O2DE-7083
Related with accessibility, when expanding a list, the focus should move to the first element of the expanded list and that's why the tabIndex prop is needed.
Locally tested:
[Screen_recording_20250311_084555.webm](https://github.com/user-attachments/assets/c1d569c4-d2ad-4a6e-b72b-63e097e63ce8)
=> feat(Row): add tabIndex prop

src/__tests__/list-test.tsx, src/list.tsx
Changes:
- On row and boxed row components, a new prop is added to customize the touchable role.
- if this prop is NOT used, the touchable continues getting the role prop is passed, else, the touchable role is used.
- This prop is not used when the row contains a control.
=> feat(Row,BoxedRow): allow overriding touchable role

src/sheet-common.tsx
Tested behaviour running a local playroom with this code:
https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8BlAFjGAXAShCWAfADoB2ABOUgEICuWWEpACgE4CWAtgIasCeZSpSZsYAZzEBeYAAoAlOUkkKQymLQQA7ukxYZwQaqFY%2BABxjxyxEDgCCAEQCSAeQD6AGUcoAKtYA0hkbkpqwQpmKWBipBlFjsWAA2FlYg3vFJ-oExsGJgHKZxTJbW9uJ57AXsTJnRMfEwnBHkANoAugG1qgC%2BHUFdclldhsqq3jAAHliGSAD0dAwiHDz8yrM62HgEyiB%2BIFgYnOIIzSAAshAAbuxiWLwg7SCa7FD7YscAjADMAGwAHK1dIA
=> feat(sheet-root): disable focus trap when running in an iframe (#1353)

css/mistica-common.css, examples/css/index.html
https://jira.tid.es/browse/WEB-2191
=> feat(mistica-css): Chip

src/__stories__/list-story.tsx, src/__stories__/stack-story.tsx, src/list.tsx, src/stack.tsx
Introduce `aria-live` and `aria-atomic` for `RowList`, `BoxedRowList` and `Stack`
`Stack` is needed because `BoxedRowList` wraps it as its first child.
In case we consider this is way too much, an alternative version exposing the props only for `RowList` is available [here](https://github.com/Telefonica/mistica-web/pull/1378).
=> feat(RowList, BoxedRowList, Stack): O2DE-7699 RowList with aria-live and aria-atomic attributes

src/__tests__/radio-button-test.tsx, src/radio-button.tsx
WEB-2262
Can be verified in [this playroom](https://mistica-3ujvm8jm3-flows-projects-65bb050e.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AhArgFwxAdgBQCcBLAWwEMCBPAAl0JgGcGBeYACgEprmA%2Ba4AL4CeAYQA2RMAGtqJGEgD06LHWLkqPADo4kAJTJQiEAOIEIaAA5ac1anogB3ADJEGGa7dv2H1DEQxiMMyaIChkOOFkIdQEBkYAamRiaEEhAEaREdEKHp7evv6BwSAAghYWgdGxhhCJyakgZOWVINQ52l4Kuo4ubtaK%2BjWm5lbaIAA0IBgAFjByDAgA2iAAshAAbq4YFCAAupMORFAzC-CLAMwAbAAMuwJAA)
=> fix(Radio): update tabIndex logic when no radio is selected

src/list.css.ts, src/list.tsx
https://jira.tid.es/browse/WEB-2167
https://github.com/user-attachments/assets/86fde2fb-5e9e-4e98-843e-ef9bbfdee9ec
=> fix(Row,BoxedRow): fix ScreenReaderOnly position for iOS VoiceOver in informative lists using aria-label
